Pulques/Controllers/TemperaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pulques.Controllers
{
    public class TemperaturaController : Controller
    {
        // GET: Temperatura
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Resultado(double Temperatura, int Seleccion)
        {
            double resultado;
            if (Seleccion == 1)
            {
                resultado = (Temperatura - 32) * (5.0 / 9.0);
            }
            else
            {
                resultado = (Temperatura * (9.0 / 5.0)) + 32;
            }

            ViewBag.Resultado = resultado;

            return View();
        }
    }
}

Pulques/Views/Temperatura/Index.cshtml
@model Pulques.Models.Conversor

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Resultado", "Temperatura", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Temperatura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Temperatura, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.RadioButtonFor(model => model.Seleccion, 1) @Html.Label("C")
            @Html.RadioButtonFor(model => model.Seleccion, 2) @Html.Label("F")
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-dark" value="Calcular" />
        </div>
    </div>
}

Pulques/Views/Temperatura/Resultado.cshtml
@{
    ViewBag.Title = "Resultado";
}

<h2>Resultado</h2>

<h3>@ViewBag.Resultado</h3>